version: "3.7"
services:
  nginx:
    image: nginx:1.25.3
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/data/static
    ports:
      - 80:80
    depends_on:
      - apop
  
  apop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apop
    networks:
      - network
    volumes:
      - ./static:/djangoproject/static
    command: >
      bash -c "
      python3 manage.py migrate&& 
      gunicorn apop2.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
  
  db:
    image: mariadb:11.1.3
    restart: always
    container_name: mariadb
    volumes:
      - mariadb-database:/var/lib/mysql
    networks:
      - network
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE : apopdb
      MARIADB_USER: example-user
      MARIADB_PASSWORD: example-password
      MARIADB_ROOT_PASSWORD: password
    

networks:
  network:

volumes:
  mariadb-database: